config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "home#index"
  get "home/index"

  namespace :admins do

    # Admin Resources
    resources :employees
    resources :students
    resources :news
    resources :departments
    resources :courses
    resources :subjects
    resources :semesters

    # Admin Custom Actions
    get '/admin_dashboard' => "dashboard#admin_dashboard"
  end

  namespace :students do
    get '/news_disply' => "custom#news_disply"
  end
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :first_name, :last_name, :middle_name, :date_of_birth, :presence => true
  validates :email, :presence => true, :uniqueness => true

  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end

end

app/controllers/admins/employees_controller.rb
class Admins::EmployeesController < ApplicationController

  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to admins_employee_path(@employee), notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: admins_employee_path(@employee) }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to admins_employee_path(@employee), notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: admins_employee_path(@employee) }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to admins_employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:first_name, :middle_name, :last_name, :date_of_birth, :date_of_joining, :qualification, :address, :city, :state, :country, :contact, :email, :department_id)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/admins/employees/_form.html.erb
<%= form_for [:admins, @employee] do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :middle_name %>
      <%= f.text_field :middle_name, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :date_of_birth %>
      <span class="fa fa-calendar errspan"></span>
      <%= f.text_field :date_of_birth, class: "form-control datepicker" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :date_of_joining %>
      <span class="fa fa-calendar errspan"></span>
      <%= f.text_field :date_of_joining, class: "form-control datepicker" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :qualification %>
      <%= f.text_field :qualification, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :state %>
      <%= f.text_field :state, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :country %>
      <%= f.text_field :country, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :contact %>
      <%= f.text_field :contact, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :department_id %>
      <%= f.text_field :department_id, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <%= f.label :address %>
      <%= f.text_area :address, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
    </div>
  </div>
  &nbsp
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
<script type="text/javascript">
  $(".datepicker").datepicker({
    format: "yyyy-mm-dd"
  });
</script>

app/views/admins/employees/edit.html.erb
<h3>Editing Employee</h3>

<%= render 'form' %>

<%= link_to 'Show', admins_employee_path(@employee) %> |
<%= link_to 'Back', admins_employees_path %>

app/views/admins/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.department_id %></td>
        <td><%= link_to 'Show', admins_employee_path(employee) %></td>
        <td><%= link_to 'Edit', edit_admins_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', admins_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_admins_employee_path %>

app/views/admins/employees/new.html.erb
<h3>New Employee</h3>

<%= render 'form' %>

<%= link_to 'Back', admins_employees_path %>

app/views/admins/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @employee.department_id %>
</p>

<%= link_to 'Edit', edit_admins_employee_path(@employee) %> |
<%= link_to 'Back', admins_employees_path %>