config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "home#index"
  get "home/index"

  namespace :admins do

    # Admin Resources
    resources :employees
    resources :students
    resources :news
    resources :departments
    resources :courses
    resources :subjects
    resources :semesters

    # Admin Custom Actions
    get '/admin_dashboard' => "dashboard#admin_dashboard"
  end

  namespace :students do
    get '/news_disply' => "custom#news_disply"
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :semester_subjects
  has_many :semesters, through: :semester_subjects
  validates :name, :presence => true
end

app/controllers/admins/subjects_controller.rb
class Admins::SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  def index
    @subjects = Subject.all
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    @subject = Subject.new(subject_params)
    respond_to do |format|
      if @subject.save
        format.js
        format.html { redirect_to admins_subject_path(@subject), notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.js
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.js
        format.html { redirect_to admins_subject_path(@subject), notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @subject.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to admins_subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_subject
      @subject = Subject.find(params[:id])
    end

    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/admins/subjects/_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Edit Subject</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/admins/subjects/_error.html.erb
<% if @subject.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h4>
    <ul>
    <% @subject.errors.full_messages.each do |message| %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><%= message %></strong>
      </div>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/subjects/_form.html.erb
<%= form_for [:admins, @subject], :remote => true do |f| %>
  <div class="modal-body">
    <div class="error-container"></div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= f.submit "Save Subject", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admins/subjects/_new.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">New Course</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/admins/subjects/_subject.html.erb
<tr id="subject_<%= subject.id%>">
  <td><%= subject.name %></td>
  <td><%= link_to 'Show', admins_subject_path(subject), class: "btn btn-info" %></td>
  <td><%= link_to 'Edit', edit_admins_subject_path(subject), :remote => true, class: "btn btn-warning" %></td>
  <td><%= link_to 'Destroy', admins_subject_path(subject), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-danger" %></td>
</tr>

app/views/admins/subjects/create.js.erb
<% if @subject.errors.count > 0 %>
  $(".error-container").html("<%= escape_javascript(render 'error') %>")
<% else %>
  $("#new-subject").modal('hide')
  $("#subject-index").append("<%= escape_javascript(render('subject', subject: @subject )) %>")
<% end %>

app/views/admins/subjects/destroy.js.erb
$("#subject_<%= @subject.id%>").remove();

app/views/admins/subjects/edit.js.erb
$("#edit-subject").html("<%= escape_javascript(render 'edit') %>")
$("#edit-subject").modal('show')

app/views/admins/subjects/index.html.erb
<div class="col-md-10">
  <p id="notice"><%= notice %></p>
  <div class="well">
    <div class="row">
      <div class="col-md-5">
        <h3>Listing Subjects</h3>
      </div>
      <div class="col-md-5">
        <h3><%= link_to 'New Subject', new_admins_subject_path, :"data-toggle" => "modal" ,:"data-target" => "#new-subject", :remote => true, class: "btn btn-primary pull-right" %></h3>
      </div>
    </div>
  </div>
  <div id="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody id="subject-index">
        <% @subjects.each do |subject| %>
          <tr id="subject_<%= subject.id%>">
            <td><%= subject.name %></td>
            <td><%= link_to 'Show', admins_subject_path(subject), class: "btn btn-info" %></td>
            <td><%= link_to 'Edit', edit_admins_subject_path(subject), :remote => true, class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', admins_subject_path(subject), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="modal fade" id="new-subject" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>
<div class="modal fade" id="edit-subject" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

app/views/admins/subjects/new.js.erb
$("#new-subject").html("<%= escape_javascript(render 'new') %>")
$("#new-subject").modal('show')

app/views/admins/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Edit', edit_admins_subject_path(@subject), :remote => true %> |
<%= link_to 'Back', admins_subjects_path %>
<div class="modal fade" id="edit-subject" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

app/views/admins/subjects/update.js.erb
<% if @subject.errors.count > 0 %>
  $(".error-container").html("<%= escape_javascript(render 'error') %>")
<% else %>
  $("#edit-subject").modal('hide')
  $('#subject_<%= @subject.id %>').replaceWith("<%= escape_javascript(render('subject', subject: @subject )) %>")
<% end %>