config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "home#index"
  get "home/index"

  namespace :admins do

    # Admin Resources
    resources :employees
    resources :students
    resources :news
    resources :departments
    resources :courses
    resources :subjects
    resources :semesters

    # Admin Custom Actions
    get '/admin_dashboard' => "dashboard#admin_dashboard"
  end

  namespace :students do
    get '/news_disply' => "custom#news_disply"
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :courses
  validates :name, :presence => true, :uniqueness => true
end

app/controllers/admins/departments_controller.rb
class Admins::DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
  end

  def edit
  end

  def create
    @department = Department.new(department_params)
    respond_to do |format|
      if @department.save
        format.html { redirect_to admins_department_path(@department), notice: 'Department was successfully updated.' }
        format.js
        format.json { render :show, status: :created, location: @department }
      else
        format.js
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to admins_department_path(@department), notice: 'Department was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @department }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to admins_departments_url, notice: 'Department was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  private

    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/admins/departments/_department.html.erb
<tr id="department_<%= department.id%>">
  <td><%= department.name %></td>
  <td><%= link_to 'Show', admins_department_path(department), class: "btn btn-info" %></td>
  <td><%= link_to 'Edit', edit_admins_department_path(department),:remote => true, class: "btn btn-warning" %></td>
  <td><%= link_to 'Destroy', admins_department_path(department), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-danger" %></td>
</tr>

app/views/admins/departments/_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Edit Department</h4>
    </div>
    <%= render "form" %>
  </div>
</div>

app/views/admins/departments/_error.html.erb
<% if @department.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h4>
    <ul>
    <% @department.errors.full_messages.each do |message| %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><%= message %></strong>
      </div>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/departments/_form.html.erb
<%= form_for [:admins, @department], :remote => true do |f| %>
  <div class="modal-body">
    <div class="error-container"></div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= f.submit "Save Department", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admins/departments/_new.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Department</h4>
      </div>
      <%= render "form" %>
    </div>
</div>

app/views/admins/departments/create.js.erb
<% if @department.errors.count > 0 %>
  $(".error-container").html("<%= escape_javascript(render 'error') %>")
<% else %>
  $("#new-department").modal('hide')
  $("#department-index").append("<%= escape_javascript(render('department', department: @department )) %>")
<% end %>

app/views/admins/departments/destroy.js.erb
$("#department_<%= @department.id%>").remove();

app/views/admins/departments/edit.js.erb
$("#edit-department").html("<%= escape_javascript(render 'edit') %>")
$("#edit-department").modal('show')

app/views/admins/departments/index.html.erb
<div class="col-md-10">
  <p id="notice"><%= notice %></p>
  <div class="well">
    <div class="row">
      <div class="col-md-5">
        <h3>Listing Departments</h3>
      </div>
      <div class="col-md-5">
        <h3><%= link_to 'New Department', new_admins_department_path, :"data-toggle" => "modal" ,:"data-target" => "#new-department", :remote => true, class: "btn btn-primary pull-right" %></h3>
      </div>
    </div>
  </div>
  <div id="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3">Action</th>
        </tr>
      </thead>
      <tbody id="department-index">
        <% @departments.each do |department| %>
          <tr id="department_<%= department.id%>">
            <td><%= department.name %></td>
            <td><%= link_to 'Show', admins_department_path(department), class: "btn btn-info" %></td>
            <td><%= link_to 'Edit', edit_admins_department_path(department),:remote => true, class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', admins_department_path(department), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>
<div class="modal fade" id="new-department" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>
<div class="modal fade" id="edit-department" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

app/views/admins/departments/new.js.erb
$("#new-department").html("<%= escape_javascript(render 'new') %>")
$("#new-department").modal('show')

app/views/admins/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<%= link_to 'Edit', edit_admins_department_path(@department), :remote => true %> |
<%= link_to 'Back', admins_departments_path %>
<div class="modal fade" id="edit-department" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

app/views/admins/departments/update.js.erb
<% if @department.errors.count > 0 %>
  $(".error-container").html("<%= escape_javascript(render 'error') %>")
<% else %>
  $("#edit-department").modal('hide')
  $('#department_<%= @department.id %>').replaceWith("<%= escape_javascript(render('department', department: @department )) %>")
<% end %>