config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "home#index"
  get "home/index"

  namespace :admins do

    # Admin Resources
    resources :employees
    resources :students
    resources :news
    resources :departments
    resources :courses
    resources :subjects
    resources :semesters

    # Admin Custom Actions
    get '/admin_dashboard' => "dashboard#admin_dashboard"
  end

  namespace :students do
    get '/news_disply' => "custom#news_disply"
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :first_name, :last_name, :middle_name, :date_of_birth, :admission_date, :enrollment_date, :presence => true
  validates :admission_number, :enrollment_number, :email, :presence => true, :uniqueness => true

  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end

end

app/controllers/admins/students_controller.rb
class Admins::StudentsController < ApplicationController

  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to admins_student_path(@student), notice: 'Student was successfully created.' }
        format.js {}
        format.json { render :show, status: :created, location: admins_student_path(@student) }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to admins_student_path(@student), notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: admins_student_path(@student) }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to admins_students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:first_name, :middle_name, :last_name, :date_of_birth, :age, :contact, :address, :city, :state, :country, :course_id, :email, :enrollment_number, :admission_number, :admission_date, :enrollment_date, :blood_group, :relegion, :category)
    end
end

app/controllers/students/custom_controller.rb
class Students::CustomController < ApplicationController
  layout 'students'
  def news_disply
    @latest_news = News.all
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins/students/_form.html.erb
<%= form_for [:admins, @student] do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <div class="jumbotron col-md-11">
        <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
        <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :middle_name %>
      <%= f.text_field :middle_name, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :date_of_birth %>
      <span class="fa fa-calendar errspan"></span>
      <%= f.text_field :date_of_birth, class: "form-control datepicker" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :age %>
      <%= f.text_field :age, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :contact %>
      <%= f.text_field :contact, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :state %>
      <%= f.text_field :state, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :country %>
      <%= f.text_field :country, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :enrollment_date %>
      <span class="fa fa-calendar errspan"></span>
      <%= f.text_field :enrollment_date, class: "form-control datepicker" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :admission_date %>
      <span class="fa fa-calendar errspan"></span>
      <%= f.text_field :admission_date, class: "form-control datepicker" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :admission_number %>
      <%= f.text_field :admission_number, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :enrollment_number %>
      <%= f.text_field :enrollment_number, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :blood_group %>
      <%= f.text_field :blood_group, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :relegion %>
      <%= f.text_field :relegion, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3 col-xs-12">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :course_id %>
      <%= f.text_field :course_id, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
      <%= f.label :category %>
      <%= f.text_field :category, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-xs-12">
      <%= f.label :address %>
      <%= f.text_area :address, class: "form-control" %>
    </div>
    <div class="col-md-3 col-xs-12">
    </div>
  </div>
  &nbsp

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
<script type="text/javascript">
  $(".datepicker").datepicker({
    format: "yyyy-mm-dd"
  });
</script>

app/views/admins/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', admins_student_path(@student) %> |
<%= link_to 'Back', admins_students_path %>

app/views/admins/students/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Listing Students</h3>
<div id="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>DOB</th>
        <th>Course</th>
        <th>Email</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.full_name %></td>
          <td><%= student.date_of_birth %></td>
          <td><%= student.course_id %></td>
          <td><%= student.email %></td>
          <td><%= student.address %></td>
          <td><%= link_to 'Show', admins_student_path(student), class: "btn btn-info" %></td>
          <td><%= link_to 'Edit', edit_admins_student_path(student), class: "btn btn-warning" %></td>
          <td><%= link_to 'Destroy', admins_student_path(student), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'New Student', new_admins_student_path, class: "btn btn-primary" %>

app/views/admins/students/new.html.erb
<h3>New Student</h3>

<%= render 'form' %>

<%= link_to 'Back', admins_students_path %>

app/views/admins/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blood group:</strong>
  <%= @student.blood_group %>
</p>

<p>
  <strong>Relegion:</strong>
  <%= @student.relegion %>
</p>

<p>
  <strong>Category:</strong>
  <%= @student.category %>
</p>

<%= link_to 'Edit', edit_admins_student_path(@student) %> |
<%= link_to 'Back', admins_students_path %>